export { default as ImageSlider } from "./components/ImageSlider"
export { default as Info } from "./components/Info"
export { default as EditImagesSlider } from "./components/EditComponents/ImagesSlider"
export { default as EditInterests } from "./components/EditComponents/EditInterests"
export { default as EditProfile } from "./components/EditComponents/EditProfile"
